### ISSUE TITLE
Idea/Gradle/Module Issues

### ISSUE THREAD

**Issue by gudenau** [discord-java/opus-java#3]
I am getting a really strange error related to the POM for this project in Idea after adding a `module-info.java` to my project.

![Error: javaL .../opus-java-1.0.4.pom](https://user-images.githubusercontent.com/5642329/58447759-1759fa80-80cb-11e9-93fa-04374e409898.png)

Idea version: Ultimate 2019.1
Gradle version: 4.10
Javac Version: 12

build.gradle:
```
plugins {
    id 'java'
}

group 'net.gudenau.discord.bot'
version '1.0-SNAPSHOT'

sourceCompatibility = 12

compileJava {
    inputs.property('moduleName', 'net.gudenau.discord.DiscordBot.main')
    doFirst {
        options.compilerArgs = [
                '--module-path', classpath.asPath
        ]
        classpath = files()
    }
}

repositories {
    mavenCentral()
    jcenter()
}

dependencies {
    testCompile group: 'junit', name: 'junit', version: '4.12'

    implementation 'net.dv8tion:JDA:3.8.3_463'
    implementation 'com.microsoft.azure.cognitiveservices:azure-cognitiveservices-imagesearch:1.0.1'
    implementation 'com.google.code.gson:gson:2.8.5'
    implementation 'com.squareup.okhttp3:okhttp:3.14.2'
}
```

I am not sure who's at fault here, figured I should start here since your POM is referenced.

**Comment by MinnDevelopment** [comment]
You are adding a pom file to the module-path which is not allowed. [See here for an example](https://github.com/JDA-Applications/jda-sample-jdk9/blob/5b6e504a1dfb131d5e31c145903f1dec76d77521/core/build.gradle#L44) to fix your issue.

**Comment by gudenau** [comment]
That looks exactly the same as what I had in my build.gradle.

**Comment by MinnDevelopment** [comment]
```diff
+        def path = classpath.asPath.split(";").findAll {
+            it.endsWith '.jar'
+        }.join(";")
         options.compilerArgs = [
-                '--module-path', classpath.asPath
+                '--module-path', path
         ]
```

**Comment by gudenau** [comment]
No change, is this a gradle bug?

**Comment by MinnDevelopment** [comment]
This seems to be an issue with gradle: https://github.com/gradle/gradle/issues/8582
